// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateEmployeeParams struct {
	FirstName    string `json:"FirstName"`
	LastName     string `json:"LastName"`
	Username     string `json:"Username"`
	Email        string `json:"Email"`
	Password     string `json:"Password"`
	Dob          string `json:"DOB"`
	DepartmentID int    `json:"DepartmentID"`
	Position     string `json:"Position"`
}

type Department struct {
	DepartmentID string `json:"DepartmentID"`
	Name         string `json:"Name"`
}

type Employee struct {
	EmployeeID string      `json:"EmployeeID"`
	FirstName  string      `json:"FirstName"`
	LastName   string      `json:"LastName"`
	Username   string      `json:"Username"`
	Email      string      `json:"Email"`
	Dob        string      `json:"DOB"`
	Department *Department `json:"Department"`
	Position   string      `json:"Position"`
}

type Response struct {
	Status int    `json:"Status"`
	Msg    string `json:"Msg"`
}

type UpdateEmployeeParams struct {
	FirstName    string `json:"FirstName"`
	LastName     string `json:"LastName"`
	Username     string `json:"Username"`
	Dob          string `json:"DOB"`
	DepartmentID int    `json:"DepartmentID"`
	Position     string `json:"Position"`
}
